import { Exercise } from '@/types';

export const MASTER_EXERCISE_DATABASE: Exercise[] = [
  {
    id: 'squat-back',
    name: 'Back Squat',
    sets: 4,
    reps: '6-8',
    rest: 120,
    kneeSafeLevel: 'caution',
    notes: 'Control depth based on pain level',
    substitution: 'Box squat with limited ROM',
    rationale: 'Builds overall lower body strength with controlled knee flexion.',
    sportRelevance: {
      gym: { role: 'primary', purpose: 'Foundation movement for overall leg development' },
      running: { role: 'secondary', purpose: 'Strengthens quads and glutes for power generation' },
      martial_arts: { role: 'primary', purpose: 'Essential for stance strength and explosive power' },
    },
  },
  {
    id: 'squat-front',
    name: 'Front Squat',
    sets: 3,
    reps: '8-10',
    rest: 120,
    kneeSafeLevel: 'caution',
    notes: 'More quad-dominant. Monitor knee pain.',
    substitution: 'Goblet squat',
    rationale: 'Emphasizes quad strength with upright torso position.',
    sportRelevance: {
      gym: { role: 'primary', purpose: 'Quad-focused variation for balanced leg development' },
      martial_arts: { role: 'primary', purpose: 'Mimics fighting stance and improves front leg power' },
    },
  },
  {
    id: 'squat-goblet',
    name: 'Goblet Squat',
    sets: 3,
    reps: '10-12',
    rest: 90,
    kneeSafeLevel: 'modified',
    notes: 'Lighter load. Focus on form.',
    rationale: 'Safe squat variation with reduced loading and improved form feedback.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Beginner-friendly squat pattern for muscle activation' },
      running: { role: 'secondary', purpose: 'Strengthens legs without excessive load on knees' },
      martial_arts: { role: 'accessory', purpose: 'Reinforces proper squat mechanics' },
    },
  },
  {
    id: 'rdl',
    name: 'Romanian Deadlift',
    sets: 3,
    reps: '10-12',
    rest: 90,
    kneeSafeLevel: 'safe',
    notes: 'Minimal knee involvement',
    rationale: 'Posterior chain builder that limits shear force on the knee.',
    sportRelevance: {
      gym: { role: 'primary', purpose: 'Hamstring and glute development with minimal knee stress' },
      running: { role: 'primary', purpose: 'Strengthens posterior chain critical for running economy' },
      martial_arts: { role: 'secondary', purpose: 'Hip hinge strength for grappling and takedown defense' },
    },
  },
  {
    id: 'deadlift-conventional',
    name: 'Conventional Deadlift',
    sets: 3,
    reps: '5-8',
    rest: 180,
    kneeSafeLevel: 'modified',
    notes: 'Start with lighter weight. Monitor knee position.',
    rationale: 'Full-body strength builder with moderate knee involvement.',
    sportRelevance: {
      gym: { role: 'primary', purpose: 'Fundamental strength movement for overall power development' },
      martial_arts: { role: 'primary', purpose: 'Builds pulling strength and grip for grappling' },
    },
  },
  {
    id: 'deadlift-trap-bar',
    name: 'Trap Bar Deadlift',
    sets: 3,
    reps: '8-10',
    rest: 120,
    kneeSafeLevel: 'modified',
    notes: 'More quad involvement than conventional',
    rationale: 'Deadlift variation with more natural movement pattern.',
    sportRelevance: {
      gym: { role: 'primary', purpose: 'Safer deadlift alternative for quad and posterior chain' },
      running: { role: 'secondary', purpose: 'Develops power without spinal loading' },
      martial_arts: { role: 'secondary', purpose: 'General strength and explosive power' },
    },
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    sets: 3,
    reps: '8-10 each',
    rest: 90,
    kneeSafeLevel: 'caution',
    notes: 'Single-leg work. Control the descent.',
    substitution: 'Reverse lunge',
    rationale: 'Unilateral strength and balance with controlled knee flexion.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Addresses strength imbalances and improves stability' },
      running: { role: 'primary', purpose: 'Single-leg strength critical for running mechanics' },
      martial_arts: { role: 'primary', purpose: 'Develops stance stability and single-leg power for kicking' },
    },
  },
  {
    id: 'step-ups',
    name: 'Step-Ups',
    sets: 3,
    reps: '10-12 each',
    rest: 60,
    kneeSafeLevel: 'modified',
    notes: 'Start with lower box height',
    rationale: 'Functional single-leg movement with controlled knee extension.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Functional leg strength and stability' },
      running: { role: 'primary', purpose: 'Mimics running motion and builds single-leg power' },
      martial_arts: { role: 'secondary', purpose: 'Improves footwork and level changes' },
    },
  },
  {
    id: 'walking-lunges',
    name: 'Walking Lunges',
    sets: 3,
    reps: '10 each leg',
    rest: 90,
    kneeSafeLevel: 'caution',
    notes: 'Avoid if knee pain exceeds 4/10',
    substitution: 'Reverse lunge (stationary)',
    rationale: 'Dynamic single-leg strength with balance component.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Functional leg work with balance and coordination' },
      running: { role: 'secondary', purpose: 'Strengthens stride mechanics and hip stability' },
      martial_arts: { role: 'primary', purpose: 'Mimics fighting footwork and stance transitions' },
    },
  },
  {
    id: 'reverse-lunges',
    name: 'Reverse Lunges',
    sets: 3,
    reps: '10 each leg',
    rest: 90,
    kneeSafeLevel: 'modified',
    notes: 'Easier on knees than forward lunges',
    rationale: 'Single-leg strength with reduced shear force on knee.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Knee-friendly single-leg development' },
      running: { role: 'secondary', purpose: 'Builds leg strength with lower impact' },
      martial_arts: { role: 'secondary', purpose: 'Reinforces backward movement patterns' },
    },
  },
  {
    id: 'hip-thrusts',
    name: 'Hip Thrusts',
    sets: 3,
    reps: '12-15',
    rest: 90,
    kneeSafeLevel: 'safe',
    notes: 'Focus on glute activation',
    rationale: 'High glute activation with minimal knee flexion angle.',
    sportRelevance: {
      gym: { role: 'primary', purpose: 'Maximal glute development with knee safety' },
      running: { role: 'primary', purpose: 'Strengthens primary running muscle with hip extension focus' },
      martial_arts: { role: 'secondary', purpose: 'Hip power for kicks and explosive movements' },
    },
  },
  {
    id: 'glute-bridge',
    name: 'Glute Bridge',
    sets: 3,
    reps: '15-20',
    rest: 60,
    kneeSafeLevel: 'safe',
    notes: 'Bodyweight or add load',
    rationale: 'Glute activation with minimal knee stress.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Glute activation and endurance' },
      running: { role: 'secondary', purpose: 'Strengthens hip extensors for efficient stride' },
      martial_arts: { role: 'accessory', purpose: 'Core stability and hip strength' },
    },
  },
  {
    id: 'hamstring-curl',
    name: 'Hamstring Curl',
    sets: 3,
    reps: '12-15',
    rest: 60,
    kneeSafeLevel: 'caution',
    notes: 'Monitor for pain behind knee',
    substitution: 'Swiss ball hamstring curl',
    rationale: 'Direct hamstring work. Monitor for discomfort behind the knee.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Isolated hamstring development' },
      running: { role: 'secondary', purpose: 'Strengthens knee flexors for stride mechanics' },
      martial_arts: { role: 'accessory', purpose: 'Protects knee during kicking movements' },
    },
  },
  {
    id: 'good-mornings',
    name: 'Good Mornings',
    sets: 3,
    reps: '10-12',
    rest: 90,
    kneeSafeLevel: 'safe',
    notes: 'Light weight. Focus on form.',
    rationale: 'Hip hinge pattern with hamstring and lower back engagement.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Posterior chain accessory movement' },
      running: { role: 'secondary', purpose: 'Strengthens running posture muscles' },
      martial_arts: { role: 'accessory', purpose: 'Hip hinge strength for grappling' },
    },
  },
  {
    id: 'bench-press',
    name: 'Bench Press',
    sets: 4,
    reps: '6-10',
    rest: 120,
    kneeSafeLevel: 'safe',
    notes: 'No knee involvement',
    rationale: 'Primary horizontal pressing movement with zero knee impact.',
    sportRelevance: {
      gym: { role: 'primary', purpose: 'Foundation upper body pressing strength' },
      martial_arts: { role: 'primary', purpose: 'Develops punching power and pushing strength' },
    },
  },
  {
    id: 'incline-bench-press',
    name: 'Incline Bench Press',
    sets: 3,
    reps: '8-12',
    rest: 120,
    kneeSafeLevel: 'safe',
    rationale: 'Upper chest development with no lower body stress.',
    sportRelevance: {
      gym: { role: 'primary', purpose: 'Upper chest focus for balanced development' },
      martial_arts: { role: 'secondary', purpose: 'Angles relevant to upward striking' },
    },
  },
  {
    id: 'push-ups',
    name: 'Push-Ups',
    sets: 3,
    reps: '12-20',
    rest: 60,
    kneeSafeLevel: 'safe',
    notes: 'Can modify to knees if needed',
    rationale: 'Bodyweight pressing with core stability requirement.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Bodyweight pressing endurance' },
      running: { role: 'accessory', purpose: 'Upper body endurance and core stability' },
      martial_arts: { role: 'primary', purpose: 'Functional pushing strength from floor positions' },
    },
  },
  {
    id: 'dips',
    name: 'Dips',
    sets: 3,
    reps: '8-12',
    rest: 90,
    kneeSafeLevel: 'safe',
    rationale: 'Compound upper body pressing with tricep emphasis.',
    sportRelevance: {
      gym: { role: 'primary', purpose: 'Compound pressing for chest and triceps' },
      martial_arts: { role: 'secondary', purpose: 'Pushing strength for clinch work' },
    },
  },
  {
    id: 'overhead-press',
    name: 'Overhead Press',
    sets: 3,
    reps: '6-10',
    rest: 120,
    kneeSafeLevel: 'safe',
    rationale: 'Vertical pressing movement with full-body stability.',
    sportRelevance: {
      gym: { role: 'primary', purpose: 'Shoulder strength and overhead power' },
      martial_arts: { role: 'secondary', purpose: 'Overhead clinch strength and stability' },
    },
  },
  {
    id: 'landmine-press',
    name: 'Landmine Press',
    sets: 3,
    reps: '8-12 each',
    rest: 90,
    kneeSafeLevel: 'safe',
    rationale: 'Angled pressing pattern with shoulder-friendly mechanics.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Shoulder pressing with reduced stress' },
      martial_arts: { role: 'primary', purpose: 'Mimics punching angle and rotational power' },
    },
  },
  {
    id: 'pull-ups',
    name: 'Pull-Ups',
    sets: 3,
    reps: '6-10',
    rest: 120,
    kneeSafeLevel: 'safe',
    notes: 'Use assistance if needed',
    rationale: 'Primary vertical pulling movement for back development.',
    sportRelevance: {
      gym: { role: 'primary', purpose: 'Upper back and lat strength development' },
      martial_arts: { role: 'primary', purpose: 'Pulling strength for grappling and clinch control' },
    },
  },
  {
    id: 'chin-ups',
    name: 'Chin-Ups',
    sets: 3,
    reps: '6-10',
    rest: 120,
    kneeSafeLevel: 'safe',
    rationale: 'Supinated grip pulling with increased bicep involvement.',
    sportRelevance: {
      gym: { role: 'primary', purpose: 'Bicep and back development' },
      martial_arts: { role: 'primary', purpose: 'Pulling patterns for submissions and control' },
    },
  },
  {
    id: 'barbell-rows',
    name: 'Barbell Rows',
    sets: 3,
    reps: '8-12',
    rest: 90,
    kneeSafeLevel: 'safe',
    notes: 'Maintain neutral spine',
    rationale: 'Horizontal pulling with posterior chain engagement.',
    sportRelevance: {
      gym: { role: 'primary', purpose: 'Back thickness and rowing strength' },
      martial_arts: { role: 'primary', purpose: 'Pulling strength for takedowns and control' },
    },
  },
  {
    id: 'dumbbell-rows',
    name: 'Dumbbell Rows',
    sets: 3,
    reps: '10-12 each',
    rest: 90,
    kneeSafeLevel: 'safe',
    rationale: 'Unilateral pulling to address imbalances.',
    sportRelevance: {
      gym: { role: 'primary', purpose: 'Back development with unilateral focus' },
      martial_arts: { role: 'secondary', purpose: 'Single-arm pulling for grappling' },
    },
  },
  {
    id: 'lat-pulldowns',
    name: 'Lat Pulldowns',
    sets: 3,
    reps: '10-12',
    rest: 90,
    kneeSafeLevel: 'safe',
    rationale: 'Vertical pulling alternative to pull-ups.',
    sportRelevance: {
      gym: { role: 'primary', purpose: 'Lat development with controlled loading' },
      martial_arts: { role: 'secondary', purpose: 'Pulling strength development' },
    },
  },
  {
    id: 'face-pulls',
    name: 'Face Pulls',
    sets: 3,
    reps: '15-20',
    rest: 60,
    kneeSafeLevel: 'safe',
    rationale: 'Rear delt and upper back health movement.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Shoulder health and posture' },
      running: { role: 'accessory', purpose: 'Upper back strength for running posture' },
      martial_arts: { role: 'secondary', purpose: 'Rear delt strength for defensive postures' },
    },
  },
  {
    id: 'planks',
    name: 'Planks',
    sets: 3,
    reps: '30-60s',
    rest: 60,
    kneeSafeLevel: 'safe',
    rationale: 'Fundamental core stability exercise.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Core stability for all lifts' },
      running: { role: 'primary', purpose: 'Core endurance for running efficiency' },
      martial_arts: { role: 'primary', purpose: 'Core stability for power transfer and defense' },
    },
  },
  {
    id: 'side-planks',
    name: 'Side Planks',
    sets: 3,
    reps: '30-45s each',
    rest: 60,
    kneeSafeLevel: 'safe',
    rationale: 'Lateral core stability and oblique strength.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Lateral core stability' },
      running: { role: 'primary', purpose: 'Lateral stability prevents energy leaks during running' },
      martial_arts: { role: 'secondary', purpose: 'Oblique strength for rotational power' },
    },
  },
  {
    id: 'dead-bugs',
    name: 'Dead Bugs',
    sets: 3,
    reps: '10 each side',
    rest: 60,
    kneeSafeLevel: 'safe',
    rationale: 'Anti-extension core movement with coordination.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Core control and anti-extension strength' },
      running: { role: 'secondary', purpose: 'Coordinated core stability' },
      martial_arts: { role: 'accessory', purpose: 'Core control for defensive positions' },
    },
  },
  {
    id: 'hanging-knee-raises',
    name: 'Hanging Knee Raises',
    sets: 3,
    reps: '10-15',
    rest: 60,
    kneeSafeLevel: 'safe',
    rationale: 'Core flexion movement with grip component.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Lower ab development and grip strength' },
      martial_arts: { role: 'secondary', purpose: 'Core strength for guard work and kicks' },
    },
  },
  {
    id: 'russian-twists',
    name: 'Russian Twists',
    sets: 3,
    reps: '20 total',
    rest: 60,
    kneeSafeLevel: 'safe',
    rationale: 'Rotational core strength with oblique emphasis.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Rotational core endurance' },
      martial_arts: { role: 'primary', purpose: 'Rotational power for strikes and throws' },
    },
  },
  {
    id: 'cable-woodchoppers',
    name: 'Cable Woodchoppers',
    sets: 3,
    reps: '12 each side',
    rest: 60,
    kneeSafeLevel: 'safe',
    rationale: 'Dynamic rotational movement for oblique strength.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Functional rotational strength' },
      martial_arts: { role: 'primary', purpose: 'Mimics rotational striking and throwing patterns' },
    },
  },
  {
    id: 'pallof-press',
    name: 'Pallof Press',
    sets: 3,
    reps: '10 each side',
    rest: 60,
    kneeSafeLevel: 'safe',
    rationale: 'Anti-rotation core stability exercise.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Core stability and anti-rotation strength' },
      running: { role: 'secondary', purpose: 'Prevents torso rotation during running' },
      martial_arts: { role: 'primary', purpose: 'Core stability against rotational forces in grappling' },
    },
  },
  {
    id: 'medicine-ball-throws',
    name: 'Medicine Ball Rotational Throws',
    sets: 3,
    reps: '8 each side',
    rest: 90,
    kneeSafeLevel: 'safe',
    notes: 'Explosive movement',
    rationale: 'Explosive rotational power development.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Power and explosiveness training' },
      martial_arts: { role: 'primary', purpose: 'Develops explosive rotational power for striking' },
    },
  },
  {
    id: 'farmers-carry',
    name: 'Farmers Carry',
    sets: 3,
    reps: '40-60m',
    rest: 90,
    kneeSafeLevel: 'safe',
    notes: 'Heavy load. Walk controlled.',
    rationale: 'Full-body stability and grip strength with functional carry pattern.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Grip, trap, and core strength' },
      martial_arts: { role: 'primary', purpose: 'Grip strength essential for grappling and clinch control' },
    },
  },
  {
    id: 'dead-hangs',
    name: 'Dead Hangs',
    sets: 3,
    reps: '30-45s',
    rest: 60,
    kneeSafeLevel: 'safe',
    rationale: 'Passive grip strength and shoulder health.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Grip endurance and shoulder mobility' },
      martial_arts: { role: 'primary', purpose: 'Grip endurance for submissions and control' },
    },
  },
  {
    id: 'towel-pull-ups',
    name: 'Towel Pull-Ups',
    sets: 3,
    reps: '5-8',
    rest: 120,
    kneeSafeLevel: 'safe',
    notes: 'Advanced grip variation',
    rationale: 'Pull-ups with increased grip demand.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Advanced grip and back training' },
      martial_arts: { role: 'primary', purpose: 'Gi grip strength for grappling sports' },
    },
  },
  {
    id: 'plate-pinches',
    name: 'Plate Pinches',
    sets: 3,
    reps: '20-30s',
    rest: 60,
    kneeSafeLevel: 'safe',
    rationale: 'Pinch grip strength for hand strength.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Grip strength variety' },
      martial_arts: { role: 'secondary', purpose: 'Grip strength for control positions' },
    },
  },
  {
    id: 'wrist-curls',
    name: 'Wrist Curls',
    sets: 2,
    reps: '15-20',
    rest: 45,
    kneeSafeLevel: 'safe',
    rationale: 'Forearm and wrist strength development.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Forearm development' },
      martial_arts: { role: 'secondary', purpose: 'Wrist strength for punching and grappling' },
    },
  },
  {
    id: 'jump-squats',
    name: 'Jump Squats',
    sets: 3,
    reps: '8-10',
    rest: 120,
    kneeSafeLevel: 'caution',
    notes: 'High impact. Assess pain level first.',
    substitution: 'Box squats (explosive concentric only)',
    rationale: 'Explosive lower body power with high knee impact.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Power development for athletic performance' },
      martial_arts: { role: 'primary', purpose: 'Explosive power for takedowns and level changes' },
    },
  },
  {
    id: 'box-jumps',
    name: 'Box Jumps',
    sets: 3,
    reps: '6-8',
    rest: 120,
    kneeSafeLevel: 'caution',
    notes: 'Land softly. Step down, don\'t jump down.',
    substitution: 'Step-ups (explosive)',
    rationale: 'Explosive jump training with controlled landing.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Explosive leg power' },
      martial_arts: { role: 'primary', purpose: 'Explosive power for striking and level changes' },
    },
  },
  {
    id: 'broad-jumps',
    name: 'Broad Jumps',
    sets: 3,
    reps: '5-8',
    rest: 120,
    kneeSafeLevel: 'caution',
    notes: 'Land with control',
    rationale: 'Horizontal explosive power development.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Horizontal power and athleticism' },
      running: { role: 'secondary', purpose: 'Develops horizontal force production' },
      martial_arts: { role: 'primary', purpose: 'Forward explosive power for closing distance' },
    },
  },
  {
    id: 'kettlebell-swings',
    name: 'Kettlebell Swings',
    sets: 3,
    reps: '15-20',
    rest: 90,
    kneeSafeLevel: 'modified',
    notes: 'Hip hinge movement. Monitor knee during catch phase.',
    rationale: 'Explosive hip extension with minimal knee involvement.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Posterior chain power and conditioning' },
      running: { role: 'secondary', purpose: 'Hip extension power for stride' },
      martial_arts: { role: 'primary', purpose: 'Hip snap power for kicks and throws' },
    },
  },
  {
    id: 'medicine-ball-slams',
    name: 'Medicine Ball Slams',
    sets: 3,
    reps: '10-12',
    rest: 90,
    kneeSafeLevel: 'safe',
    rationale: 'Full-body explosive power with low knee impact.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Explosive power and conditioning' },
      martial_arts: { role: 'primary', purpose: 'Explosive full-body power for striking' },
    },
  },
  {
    id: 'jump-rope',
    name: 'Jump Rope',
    sets: 3,
    reps: '2-3 min',
    rest: 60,
    kneeSafeLevel: 'caution',
    notes: 'Repetitive impact. Monitor knee response.',
    substitution: 'Shadow boxing',
    rationale: 'Cardio conditioning with repeated impact loading.',
    sportRelevance: {
      running: { role: 'secondary', purpose: 'Cardiovascular conditioning and calf strength' },
      martial_arts: { role: 'primary', purpose: 'Essential conditioning and footwork development' },
    },
  },
  {
    id: 'assault-bike',
    name: 'Assault Bike',
    sets: 4,
    reps: '30-60s',
    rest: 90,
    kneeSafeLevel: 'modified',
    notes: 'Low resistance initially',
    rationale: 'High-intensity conditioning with controllable knee load.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Conditioning and recovery work' },
      martial_arts: { role: 'primary', purpose: 'Anaerobic conditioning for fight rounds' },
    },
  },
  {
    id: 'battle-ropes',
    name: 'Battle Ropes',
    sets: 3,
    reps: '30-45s',
    rest: 90,
    kneeSafeLevel: 'safe',
    rationale: 'Upper body conditioning with minimal knee stress.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Upper body conditioning' },
      martial_arts: { role: 'primary', purpose: 'Shoulder endurance for striking volume' },
    },
  },
  {
    id: 'sled-push',
    name: 'Sled Push',
    sets: 4,
    reps: '20-30m',
    rest: 120,
    kneeSafeLevel: 'modified',
    notes: 'Start with light load',
    rationale: 'Lower body strength and conditioning with eccentric-less loading.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Conditioning and leg strength without eccentric stress' },
      running: { role: 'secondary', purpose: 'Horizontal force production' },
      martial_arts: { role: 'primary', purpose: 'Forward drive strength for clinch and takedowns' },
    },
  },
  {
    id: 'sled-pull',
    name: 'Sled Pull',
    sets: 4,
    reps: '20-30m',
    rest: 120,
    kneeSafeLevel: 'modified',
    rationale: 'Pulling conditioning with full-body engagement.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Conditioning and pulling strength' },
      martial_arts: { role: 'primary', purpose: 'Pulling strength for grappling and clinch work' },
    },
  },
  {
    id: 'burpees',
    name: 'Burpees',
    sets: 3,
    reps: '8-12',
    rest: 90,
    kneeSafeLevel: 'caution',
    notes: 'High impact. Modify if needed.',
    substitution: 'Step-back burpees',
    rationale: 'Full-body conditioning with repeated knee flexion.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Metabolic conditioning' },
      martial_arts: { role: 'primary', purpose: 'Conditioning and level change practice' },
    },
  },
  {
    id: 'shuttle-runs',
    name: 'Shuttle Runs',
    sets: 4,
    reps: '20-30s',
    rest: 90,
    kneeSafeLevel: 'caution',
    notes: 'Direction changes stress knee. Monitor closely.',
    substitution: 'Straight sprints',
    rationale: 'Agility and direction change conditioning.',
    sportRelevance: {
      running: { role: 'secondary', purpose: 'Speed and agility development' },
      martial_arts: { role: 'primary', purpose: 'Footwork agility and direction changes' },
    },
  },
  {
    id: 'incline-walks',
    name: 'Treadmill Incline Walks',
    sets: 1,
    reps: '20-30 min',
    rest: 0,
    kneeSafeLevel: 'safe',
    notes: 'Low impact cardio',
    rationale: 'Cardiovascular conditioning with minimal knee impact.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Low-impact conditioning' },
      running: { role: 'secondary', purpose: 'Aerobic base building without impact' },
    },
  },
  {
    id: 'easy-run',
    name: 'Easy Run',
    sets: 1,
    reps: '20-40 min',
    rest: 0,
    kneeSafeLevel: 'modified',
    notes: 'Conversational pace. Monitor knee during and after.',
    rationale: 'Aerobic base building with moderate knee impact.',
    sportRelevance: {
      running: { role: 'primary', purpose: 'Fundamental aerobic conditioning and running volume' },
    },
  },
  {
    id: 'tempo-run',
    name: 'Tempo Run',
    sets: 1,
    reps: '15-25 min',
    rest: 0,
    kneeSafeLevel: 'modified',
    notes: 'Comfortably hard pace. Build duration gradually.',
    rationale: 'Lactate threshold training for running performance.',
    sportRelevance: {
      running: { role: 'primary', purpose: 'Develops sustained speed and lactate threshold' },
    },
  },
  {
    id: 'interval-sprints',
    name: 'Interval Sprints',
    sets: 6,
    reps: '200-400m',
    rest: 120,
    kneeSafeLevel: 'caution',
    notes: 'High intensity. Ensure adequate warm-up.',
    rationale: 'Speed and anaerobic capacity development.',
    sportRelevance: {
      running: { role: 'primary', purpose: 'Speed development and VO2 max training' },
      martial_arts: { role: 'secondary', purpose: 'Anaerobic conditioning for fight intensity' },
    },
  },
  {
    id: 'hill-sprints',
    name: 'Hill Sprints',
    sets: 6,
    reps: '8-12s',
    rest: 180,
    kneeSafeLevel: 'modified',
    notes: 'Explosive uphill work. Walk down for recovery.',
    rationale: 'Maximum power development with reduced impact on descent.',
    sportRelevance: {
      running: { role: 'primary', purpose: 'Power and speed development with reduced impact' },
      martial_arts: { role: 'secondary', purpose: 'Explosive leg power' },
    },
  },
  {
    id: 'long-run',
    name: 'Long Run',
    sets: 1,
    reps: '60-90 min',
    rest: 0,
    kneeSafeLevel: 'modified',
    notes: 'Very easy pace. Build duration gradually.',
    rationale: 'Aerobic endurance and running economy development.',
    sportRelevance: {
      running: { role: 'primary', purpose: 'Builds aerobic base and running endurance' },
    },
  },
  {
    id: 'calf-stretch',
    name: 'Calf Stretch',
    sets: 2,
    reps: '30s each',
    rest: 0,
    kneeSafeLevel: 'safe',
    rationale: 'Maintains calf flexibility to reduce knee stress.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Maintains ankle mobility' },
      running: { role: 'primary', purpose: 'Prevents calf tightness that affects running mechanics' },
      martial_arts: { role: 'secondary', purpose: 'Ankle mobility for kicks and footwork' },
    },
  },
  {
    id: 'hip-flexor-stretch',
    name: 'Hip Flexor Stretch',
    sets: 2,
    reps: '45s each',
    rest: 0,
    kneeSafeLevel: 'safe',
    rationale: 'Reduces hip flexor tightness that can alter knee mechanics.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Hip mobility for squatting patterns' },
      running: { role: 'primary', purpose: 'Prevents hip flexor tightness from stride repetition' },
      martial_arts: { role: 'primary', purpose: 'Hip mobility for kicks and stance work' },
    },
  },
  {
    id: 'hamstring-stretch',
    name: 'Hamstring Stretch',
    sets: 2,
    reps: '30s each',
    rest: 0,
    kneeSafeLevel: 'safe',
    rationale: 'Maintains posterior chain flexibility.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Hip hinge mobility' },
      running: { role: 'primary', purpose: 'Maintains hamstring flexibility for running mechanics' },
      martial_arts: { role: 'secondary', purpose: 'Flexibility for kicks' },
    },
  },
  {
    id: 'ankle-dorsiflexion',
    name: 'Ankle Dorsiflexion Drills',
    sets: 2,
    reps: '10 each',
    rest: 0,
    kneeSafeLevel: 'safe',
    rationale: 'Improves ankle mobility which reduces knee compensation.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Ankle mobility for squat depth' },
      running: { role: 'primary', purpose: 'Ankle mobility critical for running efficiency' },
      martial_arts: { role: 'secondary', purpose: 'Footwork and kick mechanics' },
    },
  },
  {
    id: 'hip-cars',
    name: 'Hip CARs',
    sets: 2,
    reps: '5 each direction',
    rest: 0,
    kneeSafeLevel: 'safe',
    notes: 'Controlled articular rotations',
    rationale: 'Full range hip mobility to maintain joint health.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Hip mobility and joint health' },
      running: { role: 'secondary', purpose: 'Hip mobility for efficient stride' },
      martial_arts: { role: 'primary', purpose: 'Hip mobility essential for kicks and ground work' },
    },
  },
  {
    id: 'thoracic-rotations',
    name: 'Thoracic Rotations',
    sets: 2,
    reps: '10 each side',
    rest: 0,
    kneeSafeLevel: 'safe',
    rationale: 'Upper back mobility for posture and movement quality.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Upper back mobility for pressing and pulling' },
      running: { role: 'secondary', purpose: 'Torso mobility for running efficiency' },
      martial_arts: { role: 'primary', purpose: 'Rotational mobility for striking and grappling' },
    },
  },
  {
    id: 'deep-squat-hold',
    name: 'Deep Squat Holds',
    sets: 2,
    reps: '30-60s',
    rest: 0,
    kneeSafeLevel: 'caution',
    notes: 'Only if pain-free. Bodyweight only.',
    rationale: 'Maintains squat mobility and position comfort.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'Squat position mobility' },
      martial_arts: { role: 'secondary', purpose: 'Ground position comfort and mobility' },
    },
  },
  {
    id: 'neck-mobility',
    name: 'Neck Mobility',
    sets: 2,
    reps: '10 each direction',
    rest: 0,
    kneeSafeLevel: 'safe',
    rationale: 'Neck health and mobility maintenance.',
    sportRelevance: {
      gym: { role: 'accessory', purpose: 'General mobility and posture' },
      martial_arts: { role: 'primary', purpose: 'Neck strength and mobility for grappling defense' },
    },
  },
];
