import { RecoveryExercise } from '@/types';

export const RECOVERY_LIBRARY: RecoveryExercise[] = [
  // ============ REHAB / PHYSIO EXERCISES ============
  {
    id: 'spanish-squat',
    name: 'Spanish Squats',
    category: 'REHAB',
    muscleGroup: 'quadriceps',
    duration: 45,
    sets: 3,
    reps: '30-45s hold',
    impactLevel: 'NONE',
    tags: ['safe_for_acl', 'vmo_focus', 'isometric', 'patellar_tendon', 'blood_flow'],
    instructions: 'Loop a resistance band around a sturdy anchor at knee height. Step into the band behind your knees, walk back to create tension. Sit back into a squat position, letting the band support your knees. Hold the isometric position.',
    contraindications: ['acute_inflammation', 'post_surgery_early'],
    equipmentNeeded: ['resistance_band'],
    alternatives: ['wall-sit', 'tke'],
  },
  {
    id: 'tke',
    name: 'Terminal Knee Extensions (TKE)',
    category: 'REHAB',
    muscleGroup: 'quadriceps',
    duration: 30,
    sets: 3,
    reps: '15-20',
    impactLevel: 'NONE',
    tags: ['safe_for_acl', 'vmo_focus', 'knee_stability', 'post_surgery'],
    instructions: 'Loop a resistance band around a sturdy anchor at knee height. Step into the band so it sits behind your knee. Start with a slight knee bend, then fully extend the knee against band resistance. Control the return.',
    contraindications: ['acute_swelling'],
    equipmentNeeded: ['resistance_band'],
    alternatives: ['leg-extension-partial'],
  },
  {
    id: 'heel-slides',
    name: 'Heel Slides',
    category: 'REHAB',
    muscleGroup: 'quadriceps',
    duration: 30,
    sets: 3,
    reps: '10-15',
    impactLevel: 'NONE',
    tags: ['safe_for_acl', 'rom_recovery', 'post_surgery', 'gentle'],
    instructions: 'Lie on your back with legs straight. Slowly slide your heel toward your buttocks, bending the knee as far as comfortable. Hold briefly, then slowly return to start.',
    contraindications: [],
    equipmentNeeded: ['none'],
    alternatives: ['seated-knee-flexion'],
  },
  {
    id: 'slr-quad',
    name: 'Straight Leg Raises (Quad)',
    category: 'REHAB',
    muscleGroup: 'quadriceps',
    duration: 30,
    sets: 3,
    reps: '10-15',
    impactLevel: 'NONE',
    tags: ['safe_for_acl', 'vmo_focus', 'post_surgery', 'quad_activation'],
    instructions: 'Lie on your back. Tighten the quad of your injured leg, locking the knee straight. Lift the leg about 12 inches off the ground. Hold 2-3 seconds, lower slowly.',
    contraindications: [],
    equipmentNeeded: ['none'],
    alternatives: ['quad-sets'],
  },
  {
    id: 'slr-abduction',
    name: 'Straight Leg Raises (Side)',
    category: 'REHAB',
    muscleGroup: 'abductors',
    duration: 30,
    sets: 3,
    reps: '10-15 each',
    impactLevel: 'NONE',
    tags: ['safe_for_acl', 'hip_stability', 'glute_medius'],
    instructions: 'Lie on your side with bottom leg slightly bent. Keep top leg straight, toes pointing forward. Lift the top leg about 18 inches. Hold briefly, lower with control.',
    contraindications: [],
    equipmentNeeded: ['none'],
    alternatives: ['clamshells'],
  },
  {
    id: 'quad-sets',
    name: 'Quad Sets (Isometric)',
    category: 'REHAB',
    muscleGroup: 'quadriceps',
    duration: 20,
    sets: 3,
    reps: '10-15 x 5s holds',
    impactLevel: 'NONE',
    tags: ['safe_for_acl', 'vmo_focus', 'post_surgery', 'isometric', 'beginner'],
    instructions: 'Sit or lie with leg extended. Press the back of your knee down into the floor/mat, tightening your quad. Hold for 5 seconds, release. Focus on feeling the muscle above your kneecap contract.',
    contraindications: [],
    equipmentNeeded: ['none'],
    alternatives: ['slr-quad'],
  },
  {
    id: 'clamshells',
    name: 'Clamshells',
    category: 'REHAB',
    muscleGroup: 'glutes',
    duration: 30,
    sets: 3,
    reps: '15-20 each',
    impactLevel: 'NONE',
    tags: ['safe_for_acl', 'hip_stability', 'glute_medius', 'knee_valgus_prevention'],
    instructions: 'Lie on your side with knees bent at 45 degrees, feet together. Keep feet touching, rotate the top knee up toward the ceiling. Dont let your hips roll backward. Lower with control.',
    contraindications: [],
    equipmentNeeded: ['none'],
    alternatives: ['slr-abduction', 'band-walks'],
  },
  {
    id: 'patellar-mobilization',
    name: 'Patellar Mobilization',
    category: 'REHAB',
    muscleGroup: 'quadriceps',
    duration: 60,
    sets: 1,
    reps: '2 min total',
    impactLevel: 'NONE',
    tags: ['patellar_tendon', 'mobility', 'self_massage', 'post_surgery'],
    instructions: 'Sit with leg extended and relaxed. Using your thumbs, gently push your kneecap up, down, left, and right. Move slowly and within pain-free range. Spend 30 seconds in each direction.',
    contraindications: ['acute_inflammation', 'fracture'],
    equipmentNeeded: ['none'],
    alternatives: [],
  },
  {
    id: 'step-downs',
    name: 'Step Downs (Eccentric)',
    category: 'REHAB',
    muscleGroup: 'quadriceps',
    duration: 45,
    sets: 3,
    reps: '10-12 each',
    impactLevel: 'LOW',
    tags: ['safe_for_acl', 'vmo_focus', 'eccentric', 'knee_control'],
    instructions: 'Stand on a low step (4-6 inches). Slowly lower the opposite foot toward the ground by bending the standing knee. Lightly tap the floor, then return to start. Focus on control, not speed.',
    contraindications: ['acute_pain', 'severe_instability'],
    equipmentNeeded: ['box'],
    alternatives: ['tke', 'spanish-squat'],
  },
  {
    id: 'single-leg-balance',
    name: 'Single Leg Balance',
    category: 'REHAB',
    muscleGroup: 'lower_body',
    duration: 60,
    sets: 3,
    reps: '30s each leg',
    impactLevel: 'NONE',
    tags: ['safe_for_acl', 'proprioception', 'balance', 'knee_stability'],
    instructions: 'Stand on one leg with a slight knee bend. Keep your hips level and core engaged. Progress by closing eyes or standing on an unstable surface.',
    contraindications: ['severe_instability'],
    equipmentNeeded: ['none'],
    alternatives: ['tandem-stance'],
  },

  // ============ WARMUP EXERCISES ============
  {
    id: 'dynamic-leg-swings',
    name: 'Dynamic Leg Swings',
    category: 'WARMUP',
    muscleGroup: 'hip_flexors',
    duration: 30,
    sets: 1,
    reps: '10-15 each leg',
    impactLevel: 'LOW',
    tags: ['hip_mobility', 'dynamic', 'pre_workout'],
    instructions: 'Hold onto a wall or rack for balance. Swing one leg forward and backward in a controlled arc. Keep your core stable and dont twist your hips. Progress to side-to-side swings.',
    contraindications: ['acute_hip_pain'],
    equipmentNeeded: ['none'],
    alternatives: ['hip-circles'],
  },
  {
    id: 'glute-bridge-warmup',
    name: 'Glute Bridges (Activation)',
    category: 'WARMUP',
    muscleGroup: 'glutes',
    duration: 30,
    sets: 2,
    reps: '10-15',
    impactLevel: 'NONE',
    tags: ['safe_for_acl', 'glute_activation', 'hip_extension', 'pre_workout'],
    instructions: 'Lie on your back with knees bent, feet flat on floor. Drive through heels to lift hips toward ceiling, squeezing glutes at top. Lower with control.',
    contraindications: [],
    equipmentNeeded: ['none'],
    alternatives: ['hip-thrusts-bodyweight'],
  },
  {
    id: 'worlds-greatest-stretch',
    name: "World's Greatest Stretch",
    category: 'WARMUP',
    muscleGroup: 'full_body',
    duration: 60,
    sets: 1,
    reps: '5 each side',
    impactLevel: 'NONE',
    tags: ['hip_mobility', 'thoracic_mobility', 'dynamic', 'pre_workout'],
    instructions: 'Start in a push-up position. Step your right foot outside your right hand. Rotate your right arm up toward the ceiling, following with your eyes. Return hand to floor, step back, repeat other side.',
    contraindications: ['acute_back_pain'],
    equipmentNeeded: ['none'],
    alternatives: ['spiderman-stretch'],
  },
  {
    id: 'cat-cow',
    name: 'Cat-Cow Stretch',
    category: 'WARMUP',
    muscleGroup: 'lower_back',
    duration: 30,
    sets: 1,
    reps: '10 cycles',
    impactLevel: 'NONE',
    tags: ['spine_mobility', 'gentle', 'pre_workout'],
    instructions: 'Start on hands and knees. Inhale, drop belly toward floor, lift chest and tailbone (Cow). Exhale, round spine toward ceiling, tuck chin and pelvis (Cat). Flow smoothly between positions.',
    contraindications: ['acute_disc_injury'],
    equipmentNeeded: ['none'],
    alternatives: ['thoracic-rotations'],
  },
  {
    id: 'band-walks',
    name: 'Lateral Band Walks',
    category: 'WARMUP',
    muscleGroup: 'glutes',
    duration: 30,
    sets: 2,
    reps: '10-15 each direction',
    impactLevel: 'LOW',
    tags: ['safe_for_acl', 'glute_medius', 'hip_stability', 'knee_valgus_prevention'],
    instructions: 'Place a resistance band around your legs just above knees. Get into a quarter squat position. Step sideways, maintaining tension in the band. Keep toes pointing forward.',
    contraindications: [],
    equipmentNeeded: ['resistance_band'],
    alternatives: ['clamshells', 'slr-abduction'],
  },
  {
    id: 'bodyweight-squat-warmup',
    name: 'Bodyweight Squats',
    category: 'WARMUP',
    muscleGroup: 'lower_body',
    duration: 30,
    sets: 1,
    reps: '10-15',
    impactLevel: 'LOW',
    tags: ['movement_prep', 'pre_workout', 'squat_pattern'],
    instructions: 'Stand with feet shoulder-width apart. Push hips back and bend knees to lower into a squat. Keep chest up and knees tracking over toes. Drive through heels to stand.',
    contraindications: ['deep_flexion_pain'],
    equipmentNeeded: ['none'],
    alternatives: ['box-squat-warmup'],
  },
  {
    id: 'ankle-circles',
    name: 'Ankle Circles',
    category: 'WARMUP',
    muscleGroup: 'calves',
    duration: 20,
    sets: 1,
    reps: '10 each direction',
    impactLevel: 'NONE',
    tags: ['ankle_mobility', 'pre_workout', 'gentle'],
    instructions: 'Lift one foot off the ground. Rotate your ankle in slow, controlled circles. Complete all reps in one direction, then reverse.',
    contraindications: ['acute_ankle_sprain'],
    equipmentNeeded: ['none'],
    alternatives: ['ankle-dorsiflexion-drill'],
  },

  // ============ COOLDOWN / STATIC STRETCHES ============
  {
    id: 'static-hamstring-stretch',
    name: 'Static Hamstring Stretch',
    category: 'COOLDOWN',
    muscleGroup: 'hamstrings',
    duration: 45,
    sets: 2,
    reps: '30-45s each',
    impactLevel: 'NONE',
    tags: ['static', 'post_workout', 'flexibility'],
    instructions: 'Sit on the floor with one leg extended, other foot against inner thigh. Hinge forward from hips reaching toward toes. Keep back straight. Hold the stretch, breathe deeply.',
    contraindications: [],
    equipmentNeeded: ['none'],
    alternatives: ['standing-hamstring-stretch'],
  },
  {
    id: 'couch-stretch',
    name: 'Couch Stretch',
    category: 'COOLDOWN',
    muscleGroup: 'hip_flexors',
    duration: 60,
    sets: 1,
    reps: '60-90s each',
    impactLevel: 'NONE',
    tags: ['hip_flexor', 'quad_stretch', 'deep_stretch', 'post_workout'],
    instructions: 'Kneel in front of a couch or wall. Place one foot against the wall behind you, shin vertical. Step the other foot forward into a lunge. Squeeze glute of the back leg, stay upright.',
    contraindications: ['knee_flexion_pain'],
    equipmentNeeded: ['none'],
    alternatives: ['standing-quad-stretch'],
  },
  {
    id: 'pigeon-pose',
    name: 'Pigeon Pose',
    category: 'COOLDOWN',
    muscleGroup: 'glutes',
    duration: 60,
    sets: 1,
    reps: '60-90s each',
    impactLevel: 'NONE',
    tags: ['hip_opener', 'deep_stretch', 'post_workout'],
    instructions: 'From all fours, bring one knee forward behind your wrist. Extend the other leg straight back. Lower your hips toward the floor. Keep hips square. Hold and breathe.',
    contraindications: ['knee_flexion_pain', 'hip_impingement'],
    equipmentNeeded: ['none'],
    alternatives: ['figure-four-stretch'],
  },
  {
    id: 'figure-four-stretch',
    name: 'Figure Four Stretch',
    category: 'COOLDOWN',
    muscleGroup: 'glutes',
    duration: 45,
    sets: 2,
    reps: '30-45s each',
    impactLevel: 'NONE',
    tags: ['safe_for_acl', 'hip_stretch', 'piriformis', 'post_workout'],
    instructions: 'Lie on your back. Cross one ankle over the opposite knee forming a "4". Pull the bottom leg toward your chest. Feel the stretch in the crossed legs hip and glute.',
    contraindications: [],
    equipmentNeeded: ['none'],
    alternatives: ['pigeon-pose'],
  },
  {
    id: 'childs-pose',
    name: "Child's Pose",
    category: 'COOLDOWN',
    muscleGroup: 'lower_back',
    duration: 60,
    sets: 1,
    reps: '60s hold',
    impactLevel: 'NONE',
    tags: ['gentle', 'relaxation', 'back_relief', 'post_workout'],
    instructions: 'Kneel on the floor, sit back on your heels. Fold forward, extending arms in front or alongside your body. Rest forehead on the floor. Breathe deeply and relax.',
    contraindications: ['knee_flexion_pain'],
    equipmentNeeded: ['none'],
    alternatives: ['prone-press-up'],
  },
  {
    id: 'foam-roll-quads',
    name: 'Foam Rolling Quads',
    category: 'COOLDOWN',
    muscleGroup: 'quadriceps',
    duration: 60,
    sets: 1,
    reps: '60-90s each leg',
    impactLevel: 'NONE',
    tags: ['self_massage', 'recovery', 'muscle_release'],
    instructions: 'Lie face down with foam roller under your thighs. Support yourself on forearms. Roll slowly from hip to just above the knee. Pause on tender spots for 20-30 seconds.',
    contraindications: ['acute_muscle_tear'],
    equipmentNeeded: ['foam_roller'],
    alternatives: ['quad-massage'],
  },
  {
    id: 'foam-roll-it-band',
    name: 'Foam Rolling IT Band',
    category: 'COOLDOWN',
    muscleGroup: 'abductors',
    duration: 60,
    sets: 1,
    reps: '60-90s each leg',
    impactLevel: 'NONE',
    tags: ['self_massage', 'recovery', 'runners_knee'],
    instructions: 'Lie on your side with foam roller under outer thigh. Support yourself on forearm and opposite foot. Roll from hip to just above the knee. This will be intense - breathe through it.',
    contraindications: ['acute_inflammation'],
    equipmentNeeded: ['foam_roller'],
    alternatives: [],
  },
  {
    id: 'standing-calf-stretch',
    name: 'Standing Calf Stretch',
    category: 'COOLDOWN',
    muscleGroup: 'calves',
    duration: 30,
    sets: 2,
    reps: '30s each',
    impactLevel: 'NONE',
    tags: ['static', 'post_workout', 'achilles'],
    instructions: 'Stand facing a wall, hands on wall. Step one foot back, keeping heel on ground and leg straight. Lean forward until you feel stretch in calf. For soleus, slightly bend back knee.',
    contraindications: [],
    equipmentNeeded: ['none'],
    alternatives: ['step-calf-stretch'],
  },

  // ============ MOBILITY EXERCISES ============
  {
    id: 'hip-cars',
    name: 'Hip CARs',
    category: 'MOBILITY',
    muscleGroup: 'hip_flexors',
    duration: 60,
    sets: 1,
    reps: '5 each direction',
    impactLevel: 'NONE',
    tags: ['controlled_articular_rotation', 'joint_health', 'hip_mobility'],
    instructions: 'On hands and knees, lift one knee to the side. Move it in the largest possible circle: forward, up, back, down. Keep spine stable. Reverse direction. Move slowly and controlled.',
    contraindications: ['hip_impingement'],
    equipmentNeeded: ['none'],
    alternatives: ['hip-circles-standing'],
  },
  {
    id: '90-90-stretch',
    name: '90-90 Hip Stretch',
    category: 'MOBILITY',
    muscleGroup: 'hip_flexors',
    duration: 60,
    sets: 1,
    reps: '60s each side',
    impactLevel: 'NONE',
    tags: ['hip_internal_rotation', 'hip_external_rotation', 'deep_stretch'],
    instructions: 'Sit with front leg bent 90 degrees in front of you, back leg bent 90 degrees to your side. Sit tall, hinge forward over front leg. Switch sides.',
    contraindications: ['hip_impingement', 'knee_pain'],
    equipmentNeeded: ['none'],
    alternatives: ['pigeon-pose'],
  },
  {
    id: 'ankle-dorsiflexion-drill',
    name: 'Ankle Dorsiflexion Drill',
    category: 'MOBILITY',
    muscleGroup: 'calves',
    duration: 30,
    sets: 2,
    reps: '10 each',
    impactLevel: 'NONE',
    tags: ['ankle_mobility', 'squat_depth', 'knee_friendly'],
    instructions: 'Stand facing a wall, foot about 4 inches away. Drive knee forward toward wall, keeping heel down. If knee touches easily, move foot back slightly. Find the challenging distance.',
    contraindications: ['acute_ankle_sprain'],
    equipmentNeeded: ['none'],
    alternatives: ['ankle-circles'],
  },
  {
    id: 'thoracic-rotation',
    name: 'Thoracic Rotation',
    category: 'MOBILITY',
    muscleGroup: 'upper_back',
    duration: 30,
    sets: 1,
    reps: '10 each side',
    impactLevel: 'NONE',
    tags: ['thoracic_mobility', 'spine_health', 'rotation'],
    instructions: 'Start on hands and knees. Place one hand behind your head. Rotate that elbow down toward the opposite arm, then rotate up toward the ceiling. Follow the elbow with your eyes.',
    contraindications: ['acute_back_pain'],
    equipmentNeeded: ['none'],
    alternatives: ['open-book-stretch'],
  },
  {
    id: 'deep-squat-hold',
    name: 'Deep Squat Hold',
    category: 'MOBILITY',
    muscleGroup: 'lower_body',
    duration: 60,
    sets: 1,
    reps: '60-120s total',
    impactLevel: 'LOW',
    tags: ['squat_mobility', 'hip_mobility', 'ankle_mobility'],
    instructions: 'Lower into a deep squat with feet shoulder-width apart. Keep heels on ground (elevate if needed). Hold onto something for balance if necessary. Work on sitting deeper over time.',
    contraindications: ['deep_flexion_pain', 'meniscus_tear'],
    equipmentNeeded: ['none'],
    alternatives: ['goblet-squat-hold'],
  },
  {
    id: 'brettzel-stretch',
    name: 'Brettzel Stretch',
    category: 'MOBILITY',
    muscleGroup: 'full_body',
    duration: 60,
    sets: 1,
    reps: '60s each side',
    impactLevel: 'NONE',
    tags: ['thoracic_mobility', 'hip_flexor', 'rotation', 'advanced'],
    instructions: 'Lie on your side, top knee bent and held down by bottom hand. Rotate upper body, reaching top arm behind you toward the floor. Hold and breathe into the stretch.',
    contraindications: ['acute_back_pain', 'shoulder_injury'],
    equipmentNeeded: ['none'],
    alternatives: ['open-book-stretch'],
  },
];

export const getRecoveryExercisesByCategory = (category: RecoveryExercise['category']): RecoveryExercise[] => {
  return RECOVERY_LIBRARY.filter(ex => ex.category === category);
};

export const getRecoveryExercisesByTags = (tags: string[]): RecoveryExercise[] => {
  return RECOVERY_LIBRARY.filter(ex => 
    tags.some(tag => ex.tags.includes(tag))
  );
};

export const getSafeExercisesForInjury = (injuryType: string): RecoveryExercise[] => {
  const safeTagMap: Record<string, string[]> = {
    'ACL_REHAB': ['safe_for_acl', 'vmo_focus', 'isometric'],
    'PATELLAR_TENDONITIS': ['patellar_tendon', 'isometric', 'eccentric'],
    'MENISCUS_TEAR': ['safe_for_acl', 'low_flexion', 'isometric'],
    'RUNNERS_KNEE': ['runners_knee', 'hip_stability', 'glute_medius'],
    'GENERAL_PAIN': ['gentle', 'isometric', 'safe_for_acl'],
    'POST_SURGERY': ['post_surgery', 'gentle', 'rom_recovery'],
  };

  const safeTags = safeTagMap[injuryType] || safeTagMap['GENERAL_PAIN'];
  
  return RECOVERY_LIBRARY.filter(ex => 
    safeTags.some(tag => ex.tags.includes(tag)) &&
    !ex.contraindications.includes(injuryType.toLowerCase())
  );
};
